---
title: "hw5"
author: "Katya Protsenyuk"
date: '19 марта 2018 г '
output: html_document
---

### 1.1
```{r}
library(tidyverse)
library(dplyr)
library(ca)

chairs <- read.csv("https://raw.githubusercontent.com/agricolamz/2018_data_analysis_for_linguists/master/data/students/katyaprotsenyuk/hw5_CA_MCA/hw5_chairs.csv")

MCA <- MASS::mca(chairs[,-c(1,2,3)])

chairs <- cbind(chairs, MCA$rs)
variables <- as_data_frame(MCA$cs)
variables$var_names <- rownames(MCA$cs)
chairs %>% 
  ggplot(aes(`1`, `2`))+
  geom_point(aes(color = Category))+
  stat_ellipse(aes(color = Category))+
  geom_text(data = variables, aes(`1`, `2`, label = var_names))+
  theme_bw()+
  scale_x_continuous(limits = c(-0.015, 0.02))

```

### 1.2
```{r}
кажется, что Stuhl имеет свой набор свойств, отличный от набора свойств Sessel. Есть некоторые Sessel со свойствами Stuhl (розовые точки в голубом овале), как и наоборот, но кажется, что такиех точек меньше. А еще есть несколько наблюдений Stuhl, которые отличаются от основной группы наблюдений Stuhl и имеют свойства, отличные от свойств для большинства Stuhl. 
```

### 2.1
```{r}

colreg <- read.csv("https://raw.githubusercontent.com/agricolamz/2018_data_analysis_for_linguists/master/data/students/katyaprotsenyuk/hw5_CA_MCA/hw5_colreg.csv")

rownames(colreg) <- c('black', 'blue', 'brown', 'gray', 'green', 'orange', 'pink', 'purple', 'red', 'white', 'yellow')

ca <- ca(colreg)

colreg_col <- data.frame(ca$colcoord)
colreg_col$rows <- rownames(ca$colcoord)

colreg_row <- data.frame(ca$rowcoord)
colreg_row$rows <- rownames(ca$rowcoord)

colreg_col %>% 
  ggplot(aes(Dim1, Dim2, label = rows))+
  geom_text(color = "blue")+
  geom_text(data = colreg_row, color = "red")+
  theme_bw()+
  labs(x = "Dim1 (42.1%)",
       y = "Dim2 (32.6%)")


```

### 2.2

```{r}

В подкорпусе устной речи часто встречаются чертный и белый цвета, в подкорпусе печатных изданий -- цвета зеленый, красный, оранжевый (они ближе всего к press), в подкорпусе художественной литературы -- цвета желтый, синий, розовый, фиолетовый, коричневый и серый, в академической литературе -- белый цвет. 

```


